name: Build with make

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up git repository
        uses: actions/checkout@v3
      
      - name: Build plugin
        uses: coq-community/docker-coq-action@v1
        with:
          custom_image: 'coqorg/coq:8.17-ocaml-4.14-flambda'
          before_script: |
            startGroup "Install dependencies"
              sudo apt-get -y -q install binutils make csh g++ sed gawk autoconf automake autotools-dev
            endGroup
          
          script : |
            startGroup "Build the plugin with make"
              make
              make install
            endGroup